tap "adoptopenjdk/openjdk"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
tap "homebrew/services"
brew "act"
brew "bzip2"
brew "cask"
brew "certbot"
brew "cocoapods"
brew "docker"
brew "drone-cli"
brew "duti"
brew "exa"
brew "ruby"
brew "fastlane", link: false
brew "gh"
brew "gifsicle"
brew "git-filter-repo"
brew "glib"
brew "go@1.17"
brew "gradle"
brew "helm"
brew "hey"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "mackup"
brew "mas"
brew "md5sha1sum", link: false
brew "mitmproxy"
brew "nghttp2"
brew "node"
brew "php"
brew "postgresql"
brew "pre-commit"
brew "pure"
brew "pyenv"
brew "svgo"
brew "tldr"
brew "typescript"
brew "wget"
brew "wifi-password"
brew "yarn"
brew "zlib"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-you-should-use"
cask "calibre"
cask "cameracontroller"
cask "dozer"
cask "dropbox"
cask "fontplop"
cask "gitify"
cask "hyper"
cask "kap"
cask "karabiner-elements"
cask "linear-linear"
cask "obsidian"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-json"
cask "slack"
cask "sourcetree"
cask "spotify"
cask "tableplus"
cask "tresorit"
cask "vlc"
mas "Bear", id: 1091189122
mas "Bitwarden", id: 1352778147
mas "Gifski", id: 1351639930
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Save to Pocket", id: 1477385213
mas "Table Tool", id: 1122008420
mas "The Unarchiver", id: 425424353
mas "Vimari", id: 1480933944
mas "Wipr", id: 1320666476
